name: Deploy

on:
  push:
    branches:
    - dev
    # for testing
    - cicd

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Foreman
      uses: Roblox/setup-foreman@master
      with:
        version: "^1.1.0"
        token: ${{ SECRETS.GITHUB_TOKEN }}

    - name: Publish
      shell: bash
      run: rojo build -o dist.rbxl && rbxcloud experience publish -f dist.rbxl -t published -p ${{ SECRETS.DEV_PLACE_ID }} -u ${{ SECRETS.DEV_UNIVERSE_ID}} -a ${{ SECRETS.API_KEY }}
